# Generated by Django 5.0.3 on 2024-04-14 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="custom_user_groups",
                related_query_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="custom_user_permissions",
                related_query_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user permissions",
            ),
        ),
    ]
