# Generated by Django 5.0.3 on 2024-04-22 18:21

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory", "0001_initial"),
        ("outbound", "0003_initial"),
        ("storage", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="format: not required",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="inventory.category",
                verbose_name="parent category",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="pnd_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Preferred PND location for this category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="storage.pndlocation",
                verbose_name="PND Location",
            ),
        ),
        migrations.AddField(
            model_name="foodproduct",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="inventory.category",
            ),
        ),
        migrations.AddField(
            model_name="foodproduct",
            name="last_updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaladdress",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalauditlog",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="Content Type",
            ),
        ),
        migrations.AddField(
            model_name="historicalauditlog",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalauditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="historicalcategory",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcategory",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                db_constraint=False,
                help_text="format: not required",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.category",
                verbose_name="parent category",
            ),
        ),
        migrations.AddField(
            model_name="historicalcategory",
            name="pnd_location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Preferred PND location for this category",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="storage.pndlocation",
                verbose_name="PND Location",
            ),
        ),
        migrations.AddField(
            model_name="historicalfoodproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.category",
            ),
        ),
        migrations.AddField(
            model_name="historicalfoodproduct",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalfoodproduct",
            name="last_updated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalstocklevel",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalstocklevel",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="storage.location",
                verbose_name="Warehouse Location",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocklevel",
            name="pick_face",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="storage.pickface",
                verbose_name="Pick Face Location",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocklevel",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.foodproduct",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplier",
            name="address",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.address",
                verbose_name="address",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplier",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stocklevel",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_levels",
                to="storage.location",
                verbose_name="Warehouse Location",
            ),
        ),
        migrations.AddField(
            model_name="stocklevel",
            name="pick_face",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pick_face_stock_levels",
                to="storage.pickface",
                verbose_name="Pick Face Location",
            ),
        ),
        migrations.AddField(
            model_name="stocklevel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_stock_levels",
                to="inventory.foodproduct",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier",
                to="inventory.address",
                verbose_name="address",
            ),
        ),
        migrations.AddField(
            model_name="foodproduct",
            name="suppliers",
            field=models.ManyToManyField(
                related_name="products", to="inventory.supplier"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="outbound.customer",
                verbose_name="Related Customer",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="outbound.order",
                verbose_name="Related Order",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="inventory.supplier",
                verbose_name="Related Supplier",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stocklevel",
            unique_together={("location", "product", "batch_number")},
        ),
    ]
