# Generated by Django 5.0.3 on 2024-04-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_global", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(default="User", max_length=100),
        ),
    ]
