# Generated by Django 5.0.3 on 2024-04-21 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inbound", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinbound",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.foodproduct",
            ),
        ),
        migrations.AddField(
            model_name="historicalinbound",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="received by",
            ),
        ),
        migrations.AddField(
            model_name="historicalprovisionalbayassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalprovisionalbayassignment",
            name="gatehouse_booking",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inbound.gatehousebooking",
            ),
        ),
        migrations.AddField(
            model_name="historicalprovisionalbayassignment",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalputawaytask",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned FLT Driver",
            ),
        ),
        migrations.AddField(
            model_name="historicalputawaytask",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalputawaytask",
            name="pick_face",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Designated pick face for replenishment",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.pickface",
                verbose_name="Pick Face",
            ),
        ),
        migrations.AddField(
            model_name="historicalputawaytask",
            name="pnd_location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Final destination in the PND location",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.pndlocation",
                verbose_name="PND Location",
            ),
        ),
        migrations.AddField(
            model_name="historicalreceiving",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalreceiving",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Select product being received",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.foodproduct",
                verbose_name="received product",
            ),
        ),
        migrations.AddField(
            model_name="historicalreceiving",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="User who received the product",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="received by",
            ),
        ),
        migrations.AddField(
            model_name="historicalreceiving",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Select supplier of the received product",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.supplier",
                verbose_name="supplier",
            ),
        ),
        migrations.AddField(
            model_name="inbound",
            name="final_bay_assignment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inbounds",
                to="inbound.finalbayassignment",
            ),
        ),
        migrations.AddField(
            model_name="inbound",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inbounds",
                to="inventory.foodproduct",
            ),
        ),
        migrations.AddField(
            model_name="inbound",
            name="received_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inbound_receivings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="received by",
            ),
        ),
        migrations.AddField(
            model_name="historicalputawaytask",
            name="inbound",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inbound.inbound",
            ),
        ),
        migrations.AddField(
            model_name="provisionalbayassignment",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="provisionalbayassignment",
            name="gatehouse_booking",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="inbound.gatehousebooking",
            ),
        ),
        migrations.AddField(
            model_name="historicalfinalbayassignment",
            name="provisional_bay_assignment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inbound.provisionalbayassignment",
            ),
        ),
        migrations.AddField(
            model_name="finalbayassignment",
            name="provisional_bay_assignment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="inbound.provisionalbayassignment",
            ),
        ),
        migrations.AddField(
            model_name="putawaytask",
            name="assigned_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="putaway_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned FLT Driver",
            ),
        ),
        migrations.AddField(
            model_name="putawaytask",
            name="inbound",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="putaway_tasks",
                to="inbound.inbound",
            ),
        ),
        migrations.AddField(
            model_name="putawaytask",
            name="pick_face",
            field=models.ForeignKey(
                help_text="Designated pick face for replenishment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.pickface",
                verbose_name="Pick Face",
            ),
        ),
        migrations.AddField(
            model_name="putawaytask",
            name="pnd_location",
            field=models.ForeignKey(
                help_text="Final destination in the PND location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.pndlocation",
                verbose_name="PND Location",
            ),
        ),
        migrations.AddField(
            model_name="receiving",
            name="product",
            field=models.ForeignKey(
                help_text="Select product being received",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receivings",
                to="inventory.foodproduct",
                verbose_name="received product",
            ),
        ),
        migrations.AddField(
            model_name="receiving",
            name="received_by",
            field=models.ForeignKey(
                help_text="User who received the product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="received by",
            ),
        ),
        migrations.AddField(
            model_name="receiving",
            name="supplier",
            field=models.ForeignKey(
                help_text="Select supplier of the received product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receivings",
                to="inventory.supplier",
                verbose_name="supplier",
            ),
        ),
    ]
