# Generated by Django 5.0.3 on 2024-04-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbound", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gatehousebooking",
            name="paperwork",
        ),
        migrations.RemoveField(
            model_name="historicalgatehousebooking",
            name="paperwork",
        ),
        migrations.AddField(
            model_name="gatehousebooking",
            name="has_paperwork",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gatehousebooking",
            name="paperwork_description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="historicalgatehousebooking",
            name="has_paperwork",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalgatehousebooking",
            name="paperwork_description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
