# Generated by Django 5.0.3 on 2024-04-28 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbound", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="finalbayassignment",
            name="tipper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operated_tippers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Tipper",
            ),
        ),
        migrations.AddField(
            model_name="historicalfinalbayassignment",
            name="tipper",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Tipper",
            ),
        ),
    ]
