# Generated by Django 5.0.3 on 2024-04-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbound", "0003_remove_gatehousebooking_paperwork_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatehousebooking",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalgatehousebooking",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
